/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InstallersRouteImport } from './routes/installers'
import { Route as HomeownersRouteImport } from './routes/homeowners'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ProductsRuralRouteImport } from './routes/products/rural'
import { Route as ProductsResidentialRouteImport } from './routes/products/residential'
import { Route as ProductsCommercialRouteImport } from './routes/products/commercial'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies/$slug'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallersRoute = InstallersRouteImport.update({
  id: '/installers',
  path: '/installers',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeownersRoute = HomeownersRouteImport.update({
  id: '/homeowners',
  path: '/homeowners',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/products/index.lazy').then((d) => d.Route),
)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRuralRoute = ProductsRuralRouteImport.update({
  id: '/products/rural',
  path: '/products/rural',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsResidentialRoute = ProductsResidentialRouteImport.update({
  id: '/products/residential',
  path: '/products/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCommercialRoute = ProductsCommercialRouteImport.update({
  id: '/products/commercial',
  path: '/products/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/case-studies/$slug.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/homeowners': typeof HomeownersRoute
  '/installers': typeof InstallersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/products/commercial': typeof ProductsCommercialRoute
  '/products/residential': typeof ProductsResidentialRoute
  '/products/rural': typeof ProductsRuralRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/homeowners': typeof HomeownersRoute
  '/installers': typeof InstallersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/products/commercial': typeof ProductsCommercialRoute
  '/products/residential': typeof ProductsResidentialRoute
  '/products/rural': typeof ProductsRuralRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/homeowners': typeof HomeownersRoute
  '/installers': typeof InstallersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/products/commercial': typeof ProductsCommercialRoute
  '/products/residential': typeof ProductsResidentialRoute
  '/products/rural': typeof ProductsRuralRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookies'
    | '/homeowners'
    | '/installers'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/warranty'
    | '/case-studies/$slug'
    | '/products/commercial'
    | '/products/residential'
    | '/products/rural'
    | '/sitemap/xml'
    | '/case-studies'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookies'
    | '/homeowners'
    | '/installers'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/warranty'
    | '/case-studies/$slug'
    | '/products/commercial'
    | '/products/residential'
    | '/products/rural'
    | '/sitemap/xml'
    | '/case-studies'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookies'
    | '/homeowners'
    | '/installers'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/warranty'
    | '/case-studies/$slug'
    | '/products/commercial'
    | '/products/residential'
    | '/products/rural'
    | '/sitemap/xml'
    | '/case-studies/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  HomeownersRoute: typeof HomeownersRoute
  InstallersRoute: typeof InstallersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  WarrantyRoute: typeof WarrantyRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  ProductsCommercialRoute: typeof ProductsCommercialRoute
  ProductsResidentialRoute: typeof ProductsResidentialRoute
  ProductsRuralRoute: typeof ProductsRuralRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installers': {
      id: '/installers'
      path: '/installers'
      fullPath: '/installers'
      preLoaderRoute: typeof InstallersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowners': {
      id: '/homeowners'
      path: '/homeowners'
      fullPath: '/homeowners'
      preLoaderRoute: typeof HomeownersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/rural': {
      id: '/products/rural'
      path: '/products/rural'
      fullPath: '/products/rural'
      preLoaderRoute: typeof ProductsRuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/residential': {
      id: '/products/residential'
      path: '/products/residential'
      fullPath: '/products/residential'
      preLoaderRoute: typeof ProductsResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/commercial': {
      id: '/products/commercial'
      path: '/products/commercial'
      fullPath: '/products/commercial'
      preLoaderRoute: typeof ProductsCommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  HomeownersRoute: HomeownersRoute,
  InstallersRoute: InstallersRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  WarrantyRoute: WarrantyRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  ProductsCommercialRoute: ProductsCommercialRoute,
  ProductsResidentialRoute: ProductsResidentialRoute,
  ProductsRuralRoute: ProductsRuralRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
